services:
  - type: web
    name: diligencia-elite-rj
    runtime: python
    plan: starter
    autoDeploy: true
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: diligencia_db
          property: connectionString

  - type: pserv
    name: diligencia_db
    plan: starter
    ipAllowList: []
    postgresMajorVersion: 15
